name: application_1
description: A new Flutter project.
# ... (el resto de tu archivo)

flutter:
  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
    - family: Aldrich
      fonts:
        - asset: assets/fonts/Aldrich-Regular.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700